# Generated by Django 6.0.7 on 2026-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('OS', 'Out of Stock')], default='DR', max_length=2),
        ),
    ]
