# Generated by Django 6.0.7 on 2026-08-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
