# Generated by Django 6.1 on 2026-08-16 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_domain_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_status_7561cf_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=2),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'stock'], name='products_pr_status_a069c8_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
