# Generated by Django 6.0.7 on 2026-08-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
